@startuml EX1
start
:读取数据到线性表;
:查找;
:输入关键词;
:调用查找函数;
:保存查找结果到文件;
:插入;
:输入图书信息;
:调用插入函数;
:保存数据到文件;
:删除;
:输入要删除的ISBN;
:调用删除函数;
:保存数据到文件;
:修改;
:输入ISBN和新价格;
:调用修改函数;
:保存数据到文件;
:排序;
:调用排序函数;
:保存排序结果到文件;
:计数;
:统计图书数量;
:保存数量到文件;
:结束程序;
stop
@enduml